import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LoginForm from "@/components/organisms/LoginForm";
import { useRouter } from "next/router";
import { auth } from "@/utils/firebase";
import { onAuthStateChanged } from "firebase/auth";

export default function Home() {
  const router = useRouter();

  onAuthStateChanged(auth, (user) => {
    if (user) {
      router.replace("/mypage");
    }
  });

  return (
    <>
      <Head>
        <title>test:Genit Meeting App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginForm />
      </main>
    </>
  );
}
