export const agendas = [
  { option: "好きな食べ物は？" },
  { option: "最後に見た映画は？" },
  { option: "お気に入りの本は？" },
  { option: "行きたい旅行先は？" },
  { option: "今一番欲しいものは？" },
  { option: "特技や趣味は？" },
  { option: "朝型or夜型？" },
  { option: "おもしろエピソードは？" },
  { option: "お気に入りの音楽は？" },
  { option: "好きなスポーツは？" },
  { option: "最近ハマっていることは？" },
  { option: "受賞歴はある？" },
  { option: "理想のバカンス先は？" },
  { option: "好きな季節は？" },
  { option: "貯金派or消費派？" },
  { option: "影響を受けた人は？" },
  { option: "得意な料理は？" },
  { option: "習い事はしてる？" },
  { option: "夢は何？" },
  { option: "苦手な食べ物は？" },
  { option: "行きつけのレストランは？" },
  { option: "理想の週末は？" },
  { option: "ハマっている趣味は？" },
  { option: "おすすめの国は？" },
  { option: "ハマっている曲は？" },
  { option: "印象に残った映画は？" },
  { option: "得意な楽器は？" },
  { option: "感銘を受けた本は？" },
  { option: "やりたかったことは？" },
  { option: "最高の成功体験は？" },
  { option: "おいしかった食べ物は？" },
  { option: "お気に入りの休日は？" },
  { option: "特徴的な癖は？" },
  { option: "星座や血液型は？" },
  { option: "忘れられない旅行は？" },
  { option: "理想のペットは？" },
  { option: "最近見つけたアプリは？" },
  { option: "幼少期の夢は？" },
  { option: "大切な人は？" },
  { option: "好きなスポーツチームは？" },
  { option: "おすすめのドラマは？" },
  { option: "楽しかった思い出は？" },
  { option: "恥ずかしかった出来事は？" },
  { option: "得意な外国語は？" },
  { option: "お気に入りのテレビ番組は？" },
  { option: "将来やってみたいことは？" },
  { option: "感動したコンサートは？" },
  { option: "おすすめのスポットは？" },
  { option: "好きな動物は？" },
  { option: "一番遠い旅行は？" },
  { option: "印象に残った展覧会は？" },
  { option: "最近買ったお気に入りのものは？" },
  { option: "頻繁に使うアプリは？" },
  { option: "怖かった経験は？" },
  { option: "自慢できる特技は？" },
  { option: "住みたい場所は？" },
  { option: "リラックスできる瞬間は？" },
  { option: "お笑い芸人は？" },
  { option: "人生の教訓は？" },
  { option: "得意な仕事は？" },
  { option: "感銘を受けた映画の名言は？" },
  { option: "人生の挑戦は？" },
  { option: "お気に入りのアート作品は？" },
  { option: "ユニークな旅行体験は？" },
  { option: "好きなゲームは？" },
  { option: "感動した書籍のエピソードは？" },
  { option: "大切な価値観は？" },
  { option: "心を打たれた音楽は？" },
  { option: "印象に残ったドラマは？" },
  { option: "おすすめのホテルは？" },
  { option: "好きなアクティビティは？" },
  { option: "感銘を受けた歴史的な出来事は？" },
  { option: "リフレッシュする休日は？" },
  { option: "興奮したスポーツ試合は？" },
  { option: "おすすめのレジャー施設は？" },
  { option: "好きな音楽ジャンルは？" },
  { option: "感銘を受けたスピーチは？" },
  { option: "人生の成功体験は？" },
  { option: "自然の風景は？" },
  { option: "おすすめの料理は？" },
  { option: "好きな映画は？" },
  { option: "感動した劇場パフォーマンスは？" },
  { option: "心を打たれた社会問題は？" },
  { option: "刺激的な冒険は？" },
  { option: "おすすめの音楽フェスは？" },
  { option: "好きなホビーは？" },
  { option: "感銘を受けた科学的な発見は？" },
  { option: "ユニークな食べ物の体験は？" },
  { option: "心を打たれた社会運動は？" },
  { option: "おすすめのスポーツは？" },
  { option: "好きなテクノロジーは？" },
  { option: "感動したボランティア活動は？" },
  { option: "心を打たれた音楽メッセージは？" },
  { option: "ユニークな文化体験は？" },
  { option: "リラックス方法は？" },
  { option: "好きな教育方法は？" },
  { option: "感銘を受けたビジネスストーリーは？" },
  { option: "心に残る宗教体験は？" },
];

export function getRandomAgendas(
  agendas: Array<{ option: string }>
): Array<{ option: string }> {
  const randomAgendas: Array<{ option: string }> = [];
  const numOptions = 8;
  const totalAgendas = agendas.length;

  while (randomAgendas.length < numOptions) {
    const randomIndex = Math.floor(Math.random() * totalAgendas);
    const selectedAgenda = agendas[randomIndex];

    if (!randomAgendas.includes(selectedAgenda)) {
      randomAgendas.push(selectedAgenda);
    }
  }

  return randomAgendas;
}
